# frozen_string_literal: true

# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform :ios

platform :ios do
  desc "Generate App Store screenshots (iPhone + iPad)"
  lane :screenshots do
    capture_screenshots
  end

  desc "Upload screenshots to App Store Connect"
  lane :upload_screenshots do
    ensure_api_key
    upload_to_app_store(
      app_identifier:                       "codes.tim.Zili",
      screenshots_path:                     "./fastlane/screenshots",
      overwrite_screenshots:                true,
      skip_binary_upload:                   true,
      skip_metadata:                        true,
      languages:                            %w[en-US],
      force:                                true,
      run_precheck_before_submit:           false,
      ignore_language_directory_validation: true
    )
  end

  desc "Generate screenshots and upload them"
  lane :screenshots_and_upload do
    screenshots
    upload_screenshots
  end

  desc "Build and upload to TestFlight"
  lane :beta do
    ensure_api_key
    increment_build_number xcodeproj: "Zili.xcodeproj"
    build_app(
      scheme:        "Zili",
      export_method: "app-store"
    )
    upload_to_testflight
  end

  desc "Build and upload to App Store"
  lane :release do
    ensure_api_key
    increment_build_number xcodeproj: "Zili.xcodeproj"
    build_app scheme:        "Zili",
              export_method: "app-store"
    upload_to_app_store skip_metadata:     false,
                        skip_screenshots:  false,
                        submit_for_review: false

    sentry_cli(
      org_slug:        "timcodes",
      project_slug:    "zili",
      include_sources: true
    )
  end

  # Loads the App Store Connect API key the upload lanes need. Kept out of `before_all` so
  # offline lanes (like `screenshots`) don't require the private `.p8` key to be present.
  private_lane :ensure_api_key do
    app_store_connect_api_key(
      key_id:       "5HJ4894LJ5",
      issuer_id:    "69a6de7f-1ffd-47e3-e053-5b8c7c11a4d1",
      key_filepath: "./fastlane/AuthKey_5HJ4894LJ5.p8"
    )
  end
end
